name: Data Comparison Check

on:
  schedule:
    # Run every Sunday at 9 PM UTC (2 AM Monday local time in Pacific)
    - cron: '0 21 * * 0'
  
  pull_request:
    paths:
      - 'data-sharing/R/comparisons.R'
      - 'data-sharing/R/aquarius-utils.R'
      - 'data-sharing/R/utils.R'
      - '.github/workflows/data-comparison.yml'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  data-comparison:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sharing
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Read config
      id: config
      run: echo "json=$(jq -c . r-config.json)" >> $GITHUB_OUTPUT
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true
    
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: ${{ join(fromJSON(steps.config.outputs.json).packages, '\n') }}
        cache-version: 1
    
    - name: Run data comparison
      run: |
        pwd
        Rscript R/comparison.R
