name: Fetch ERDDAP data

on:
  pull_request:
    branches: main
    paths:
      - 'data-sharing/**'
  schedule:
   - cron: '0 15 * * *'  # Every day at 8am Pacific (3pm UTC)

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sharing

    steps:
    - uses: actions/checkout@v4
    
    - name: Read config
      id: config
      run: echo "json=$(jq -c . r-config.json)" >> $GITHUB_OUTPUT

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: ${{ join(fromJSON(steps.config.outputs.json).packages, '\n') }}
        cache-version: 1

    - name: Run R script
      run: Rscript ${{ fromJSON(steps.config.outputs.json).script_path }}

    - name: Record last passed dates
      if: github.event_name != 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
      with:
        commit_message: "Recording last passed measurements"
        file_pattern: "last_passed_measurements.csv"

    - name: Upload last passed measurement
      # if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: last_passed_measurements
        path: "data-sharing/last_passed_measurements.csv"
        retention-days: 30

    - name: Upload parquet file
      # if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: upload parquet
        path: "data-sharing/*.parquet"
        retention-days: 30
        