name: Fetch ERDDAP data

on:
  pull_request:
    branches: main
    paths:
      - 'data-sharing/**'
  schedule:
   - cron: '0 15 * * *'  # Every 24 hours at 3pm UTC (8am Pacific)
  workflow_dispatch: 

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sharing
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Load secret
      id: op-load-secret
      uses: 1password/load-secrets-action@v2
      with:
        export-env: true
      env:
        SENTRY_DSN: op://EIMS Administrator/prov-data-sharing-sentry-dsn/credential
    
    - name: Read config
      id: config
      run: echo "json=$(jq -c . r-config.json)" >> $GITHUB_OUTPUT

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: ${{ join(fromJSON(steps.config.outputs.json).packages, '\n') }}
        cache-version: 1

    - name: Run R script
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
      run: Rscript ${{ fromJSON(steps.config.outputs.json).script_path }}

    - name: Record last passed dates
      if: github.event_name != 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
      with:
        commit_message: "Recording last passed measurements"
        file_pattern: "data-sharing/last_passed_measurements.csv"

    - name: Upload parquet file
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: upload parquet
        path: "data-sharing/*.parquet"
        retention-days: 30
        