name: Test Sentry Integration with R

on: 
  pull_request:
    branches: [main]

jobs:
  test-sentry:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true
        
    - name: Install sentryR
      run: |
        install.packages("sentryR")
      shell: Rscript {0}
      
    - name: Test failure and send to Sentry
      run: |
        Rscript -e "
        library(sentryR)
        
        # Configure Sentry
        configure_sentry(
          dsn = '${{ secrets.SENTRY_DSN }}',
          app_name = 'github-actions-test',
          app_version = '${{ github.sha }}',
          environment = 'ci',
          tags = list(
            repository = '${{ github.repository }}',
            branch = '${{ github.ref_name }}',
            workflow = '${{ github.workflow }}'
          )
        )
        
        # Simulate a failure and capture it
        tryCatch({
          stop('This is a test error from GitHub Actions!')
        }, error = function(e) {
          capture_exception(
            error = e,
            extra = list(
              run_url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              actor = '${{ github.actor }}',
              commit = '${{ github.sha }}'
            )
          )
          stop(e)  # Re-throw to fail the job
        })
        "